version: "3.8"
services:

  # application
  web:
    image: fastapi_network
    container_name: "fastapi_network"
    restart: always
    build: ./app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app/migrations/versions:/app/migrations/versions
    links:
      - postgresql
      - memcached

  # database
  postgresql:
    container_name: "fastapi_network_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_network
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # cache
  memcached:
    container_name: "fastapi_network_cache"
    image: memcached:1.6.10-alpine
    restart: on-failure
    ports:
      - "11211:11211"
  